#[banner]
#color = "red"
#command = "hostname | figlet -f slant"

#[weather]
#url = "wttr.in/New+York,New+York?0"

#[service_status]
#Accounts = "accounts-daemon"
#Cron = "cron"

#[uptime]
#prefix = "up"

#[ssl_certificates]
#sort_method = "alphabetical"
#
#    [ssl_certificates.certs]
#    CertName1 = "/path/to/cert1.pem"
#    CertName2 = "/path/to/cert2.pem"

#[filesystems]
#root = "/"

#[fail_2_ban]
#jails = ["sshd", "anotherjail"]

#[last_login]
#sally = 2
#jimmy = 1